Document: php5-crypto
Title: Debian php5-crypto Manual
Author: <insert document author here>
Abstract: This manual describes what php5-crypto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/php5-crypto/php5-crypto.sgml.gz

Format: postscript
Files: /usr/share/doc/php5-crypto/php5-crypto.ps.gz

Format: text
Files: /usr/share/doc/php5-crypto/php5-crypto.text.gz

Format: HTML
Index: /usr/share/doc/php5-crypto/html/index.html
Files: /usr/share/doc/php5-crypto/html/*.html
